#!/usr/bin/tclsh

set hsize 128
set rsize 2048

set fh [open musicdb.txt r]
gets $fh line
gets $fh line
gets $fh line
gets $fh line
regexp {^#RAMAX=(\d+)$} $line all racount
close $fh

set fh [open musicdb.dat w]

source musicdb.txt

set c 0
dict for {fn data} $musicdbList {
  incr c
}

puts $fh "#VERSION=10"
puts $fh "# Do not edit this file."
puts $fh "#RASIZE=2048"
puts $fh "#RACOUNT=$c"

set newrrn 1
dict for {fn data} $musicdbList {
  seek $fh [expr {([dict get $data rrn] - 1) * $rsize + $hsize}]
  puts $fh "FILE\n..$fn"

  # sort it now, make it easier
  foreach {tag} [lsort [dict keys $data]] {
    if { $tag eq "FILE" } {
      continue
    }
    if { $tag eq "rrn" } {
      # make sure rrn is correct
      set value $newrrn
    }
    set value [dict get $data $tag]
    puts $fh "$tag\n..$value"
  }
  incr newrrn
}

close $fh
exit 0
