#ifndef INC_BDJ4PLAYERUI_H
#define INC_BDJ4PLAYERUI_H

enum {
  PLUI_PLAY_WHEN_QUEUED,
  PLUI_POSITION_X,
  PLUI_POSITION_Y,
  PLUI_SHOW_EXTRA_QUEUES,
  PLUI_SIZE_X,
  PLUI_SIZE_Y,
  PLUI_SWITCH_QUEUE_WHEN_EMPTY,
  SONGSEL_FILTER_POSITION_X,
  SONGSEL_FILTER_POSITION_Y,
  SONGSEL_SORT_BY,
};

#endif /* INC_BDJ4PLAYERUI_H */
