#ifndef INC_BDJOPT_H
#define INC_BDJOPT_H

#include "list.h"

typedef enum {
  OPT_ACOUSTID_CLIENT,
  OPT_ALLOWEDIT,
  OPT_ARCHIVEDIR,
  OPT_audioid_match,
  OPT_AUDIOSINK,
  OPT_AUTOORGANIZE,
  OPT_AUTOSTARTUP,
  OPT_bdj_analogclock,
  OPT_bdj_dual,
  OPT_bdj_dualmarks,
  OPT_bdjedit_embedplayer,
  OPT_bdjeditfieldlist,
  OPT_bdjedit_hidefn,
  OPT_bdjedit_playswitch,
  OPT_bdjedit_saveadv,
  OPT_bdj_hidemarquee,
  OPT_bdj_hidemarqueeonstart,
  OPT_bdj_hidemgmt,
  OPT_bdj_hidemqcont,
  OPT_bdj_histembed,
  OPT_bdj_imagedisp,
  OPT_bdj_insrequest,
  OPT_bdj_lastexpcddir,
  OPT_bdj_marqueefullscreen,
  OPT_bdjmm_dancecount,
  OPT_bdjmm_embed,
  OPT_bdjmm_hidemainmenu,
  OPT_bdjmm_lastexportbdj,
  OPT_bdjmm_lastexportdir,
  OPT_bdjmm_lastimportbdj,
  OPT_bdjmm_lastimportfn,
  OPT_bdjmm_marksel,
  OPT_bdjmm_pbcont,
  OPT_bdjmm_pbmode,
  OPT_bdjmm_playswitch,
  OPT_bdjmm_searchfieldlist,
  OPT_bdjsl_playswitch,
  OPT_bdj_tooltipdisp,
  OPT_bpm_selection,
  OPT_CBFONTSIZE,
  OPT_CHANGESPACE,
  OPT_CLPATHFMT,
  OPT_CLVAPATHFMT,
  OPT_DEBUGLVL,
  OPT_DEBUGON,
  OPT_DEFAULTVOLUME,
  OPT_DELETEDIR,
  OPT_DONEMSG,
  OPT_ENABLEIMGPLAYER,
  OPT_FADEINTIME,
  OPT_FADEOUTTIME,
  OPT_FADETYPE,
  OPT_fmsynctimestamp,
  OPT_fmversion,
  OPT_FONTSIZE,
  OPT_GAP,
  OPT_geom_clock,
  OPT_geom_countdownclock,
  OPT_geom_cs,
  OPT_HOST,
  OPT_IMAGEDIR,
  OPT_imageplayer_geom,
  OPT_INSTPASSWORD,
  OPT_ITUNESSUPPORT,
  OPT_lastbackupdir,
  OPT_lastfmfromdir,
  OPT_lastfmmusicdir,
  OPT_lastfmtodir,
  OPT_lastrafflegame,
  OPT_lastrestoredir,
  OPT_lastsort,
  OPT_LISTINGFONTSIZE,
  OPT_LOADDANCEFROMGENRE,
  OPT_main_geom,
  OPT_marquee_geom,
  OPT_MAXPLAYTIME,
  OPT_mmdisp,
  OPT_mmdisp_cc,
  OPT_mmdisp_qp,
  OPT_mmdisp_req,
  OPT_mmdisp_sl,
  OPT_mmsldisp,
  OPT_mmsltooltipdisp,
  OPT_mmttdisp,
  OPT_mmttdisp_cc,
  OPT_mmttdisp_qp,
  OPT_mmttdisp_req,
  OPT_mmttdisp_sl,
  OPT_MOBILEMARQUEE,
  OPT_MOBILEMQPORT,
  OPT_MOBILEMQTAG,
  OPT_MOBILEMQTITLE,
  OPT_MQCLOCKFONTSIZE,
  OPT_MQDANCEFONT,
  OPT_MQDANCEFONTMULT,
  OPT_MQFONT,
  OPT_MQFULLSCREEN,
  OPT_mqheight,
  OPT_MQQLEN,
  OPT_mqSize,
  OPT_mqwidth,
  OPT_MTMPDIR,
  OPT_MUSICDIR,
  OPT_MUSICDIRDFLT,
  OPT_ORIGINALDIR,
  OPT_origuibgcolor,
  OPT_PATHFMT,
  OPT_PAUSEMSG,
  OPT_PLAYER,
  OPT_PLAYEROPTIONS,
  OPT_PLAYERQLEN0,
  OPT_PLAYERQLEN1,
  OPT_PLAYERSHUTDOWNSCRIPT,
  OPT_PLAYERSTARTSCRIPT,
  OPT_PROFILENAME,
  OPT_QUEUENAME0,
  OPT_QUEUENAME1,
  OPT_QUICKPLAYENABLED,
  OPT_QUICKPLAYSHOW,
  OPT_REMCONTROLHTML,
  OPT_REMCONTROLPASS,
  OPT_REMCONTROLPORT,
  OPT_REMCONTROLSHOWDANCE,
  OPT_REMCONTROLSHOWSONG,
  OPT_REMCONTROLUSER,
  OPT_REMOTECONTROL,
  OPT_samesongkey,
  OPT_SERVERNAME,
  OPT_SERVERPASS,
  OPT_SERVERPORT,
  OPT_SERVERTYPE,
  OPT_SERVERUSER,
  OPT_SHOWALBUM,
  OPT_SHOWBPM,
  OPT_SHOWCLASSICAL,
  OPT_SHOWSTATUS,
  OPT_SHUTDOWNSCRIPT,
  OPT_SLOWDEVICE,
  OPT_slstatsdur,
  OPT_slwidth,
  OPT_STARTMAXIMIZED,
  OPT_STARTUPSCRIPT,
  OPT_UIBGCOLOR,
  OPT_UIFIXEDFONT,
  OPT_UIFONT,
  OPT_UITHEME,
  OPT_VAPATHFMT,
  OPT_VARIOUS,
  OPT_version,
  OPT_WRITETAGS,
  OPT_MAX
} bdjoptkey_t;

typedef enum {
  OPTTYPE_GLOBAL,
  OPTTYPE_PROFILE,
  OPTTYPE_MACHINE,
  OPTTYPE_MACH_PROF
} bdjopttype_t;

typedef struct {
  bdjopttype_t    optiontype;
  char            *optname;
  valuetype_t     valuetype;
} bdjoptdef_t;

#define BDJ_CONFIG_BASEFN   "bdjconfig"
#define BDJ_CONFIG_EXT      ".txt"

void    bdjoptInit (void);
void    bdjoptFree (void);

#endif /* INC_BDJOPT_H */
