#ifndef INC_BDJ4PLAYERUI_H
#define INC_BDJ4PLAYERUI_H

/* various dynamic options */
enum {
  PLUI_HIDE_MARQUEE_ON_START,
  PLUI_PLAY_WHEN_QUEUED,
  PLUI_POSITION_X,
  PLUI_POSITION_Y,
  PLUI_SHOW_EXTRA_QUEUES,
  PLUI_SIZE_X,
  PLUI_SIZE_Y,
  PLUI_SWITCH_QUEUE_WHEN_EMPTY,
  SONGSEL_FILTER_POSITION_X,
  SONGSEL_FILTER_POSITION_Y,
  SONGSEL_SORT_BY,
  MANAGE_SELFILE_POSITION_X,
  MANAGE_SELFILE_POSITION_Y,
  PLUI_KEY_MAX,
};

#endif /* INC_BDJ4PLAYERUI_H */
